name: Wanted
main: com.itharia.wanted.WantedPlugin
version: 1.2.30
api-version: '1.21'
authors: [ MoneyMantra ]
description: Villagers become hostile after theft or murder (world-gen only for theft); witness pre-event; cooldown gating; start/stop commands.

commands:
  wanted:
    description: Wanted plugin help and admin commands.
    usage: |-
      /<command> help
      /<command> reload
      /<command> start larceny
      /<command> start associate
      /<command> start murder
      /<command> stop [all]
    aliases: [ wa ]
    permission: wanted.use

permissions:
  wanted.use:
    description: Allows use of /wanted (help & start/stop).
    default: true
  wanted.reload:
    description: Allows reloading the plugin configuration.
    default: op
