name: Build Wanted (Maven, Java 21)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn -B -ntp package
      - name: Upload JAR(s)
        uses: actions/upload-artifact@v4
        with:
          name: Wanted
          path: '**/target/*.jar'
